### ISSUE TITLE
error : not able to download schema  having union type

### ISSUE THREAD

**Issue by WISKesarkar** [nautilus/gateway#197]
While working on POC for GQL federation to support multiple gql apis under one service.
I found out nautius/gateway library fails to download schema with union types in it.

for testing Please refer this [POC-example](https://github.com/wahed-tech/nautilExamples)

Issue : 
- serviceB gql schema has union named UnionTypeTest, service schema is downloaded using get-graphql-schema cli (schema is available in serviceB package and has union field with correct member types)
- When gatwayTest.go tries to fetch the schema from nautilus/gatway it fails to grab schema for union members and GQL Playground throws attached error.

![Screenshot 2023-06-30 at 19 57 38](https://github.com/nautilus/gateway/assets/74912960/515417c3-7d38-4a38-88ea-62a8c1783737)

**Comment by akshyapadma** [comment]
@WISKesarkar Have you found any solution to this? 

I am facing the same problem in case of Union.

**Comment by JohnStarich** [comment]
@WISKesarkar Thank you for opening and for sharing a very easy-to-reproduce example. :clap: 
I've reproduced and it appears this was fixed by [`github.com/nautilus/graphql@v0.0.21`](https://github.com/nautilus/graphql/releases/tag/v0.0.21).

I've [bumped](https://github.com/nautilus/gateway/pull/207) the gateway's dependency on graphql. I'll get that merged and cut a new release that includes the fix.

**Comment by JohnStarich** [comment]
New release v0.3.14 includes the fix. Please shout if this did not address your issue!
