### ISSUE TITLE
Errors aren't being passed through correctly

### ISSUE THREAD

**Issue by linchpinstudios** [nautilus/gateway#85]
I'm using a couple of services written with gqlgen. When they return errors to the gateway it is modifying the response and removing some of the data. 

The following example shows the message being sent by the service and the message being received by the client. The `path` isn't being passed along with the `extensions` being modified to only contain an empty `code`

Consumer Service Error Response:
```json
{
  "errors": [
    {
      "message": "invalid credentials",
      "path": [
        "login"
      ],
      "extensions": {
        "code": "422",
        "issue": "credentials"
      }
    }
  ],
  "data": null
}
```

Gateway Error Response (to client):
```json
{
  "data": null,
  "errors": [{
    "extensions": {
      "code": ""
    },
    "message": "invalid credentials"
  }]
}
```

**Comment by AlecAivazis** [comment]
Hey @linchpinstudios - sorry for lagging on the response.

I dug a bit deeper and it turns out this was already solved by @bk-splunk in nautilus/graphql but needed to be pulled brought into the gateway package. I opened a PR that updates the module. If you have time to verify that it fixes your problem, that would be amazing.
